### PR TITLE
- Implemented types-specific wrappers for primitive arrays.

### PR DESCRIPTION
**Pull request by dustContributor**
Signed-off-by: Facundo Etchezar <hctf90@gmail.com>

### CODE REVIEW

**Comment by dustContributor** [comment]
Yes! Success! This CLA-pull-request-signed-off thingy is complex :smile:

**Comment by svenefftinge** [comment]
thank you!

**Comment by meysholdt** [comment]
Had to revert the change in https://github.com/eclipse/xtext-lib/commit/9847b620a095f05e204e867d0717a93f4c5dd971 because it breaks support for `char[]`.

Sorry. Can you add a wrapper for `char[]`, too?

This caused the following exception in several downstream projects:
```
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.lib.IterableExtensions.head(IterableExtensions.java:119)
	at org.eclipse.xtend.core.macro.ConditionUtils.isValidJavaIdentifier(ConditionUtils.java:121)
	at org.eclipse.xtend.core.macro.ConditionUtils.checkJavaIdentifier(ConditionUtils.java:74)
	at org.eclipse.xtend.core.macro.declaration.JvmTypeDeclarationImpl.addMethod(JvmTypeDeclarationImpl.java:140)
	at test.AbstractProcessor.doTransform(AbstractProcessor.java:37)
	at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
```

**Comment by cdietrich** [comment]
boolean[] is missing as well

**Comment by dustContributor** [comment]
Ahh right! I'll add them and resubmit the PR.

**Pull request merged**
