### PR TITLE
Do not create unnecessary vars in toString or hashCode

### PR DESCRIPTION
**Pull request by tivervac**
Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

### CODE REVIEW

**Comment by tivervac** [comment]
Same changes as #72 but with fixed ip validation

**Comment by cdietrich** [comment]
replaces https://github.com/eclipse/xtext-lib/pull/72

**Comment by kthoms** [comment]
LGTM
@cdietrich WDYT?

**Comment by cdietrich** [comment]
was already approved with #72
=> LGTM

**Pull request merged**
