### PR TITLE
[427909]: add tests for StringConcatenation and optimize it

### PR DESCRIPTION
**Pull request by rovarga**
This is a set of incremental improvements to StringConcatenation,
which result in ~30% performance increase with Xtend templates.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=427909

**Comment by rovarga** [comment]
@dhuebner Not sure if you want me to split this into multiple PRs (sorry, it turned out to be too addictive), but this is just about everything I could think of doing for this issue.

The only other thing I can think of is turning segments into List<CharSequence> and share backing byte[] when we split a multi-line string -- but that would mean severing the API contract of accessor abstract methods.

**Comment by dhuebner** [comment]
@rovarga Thanks for the contribution I will review the changes and merge asap

**Comment by dhuebner** [comment]
@rovarga Looks good so far. I will merge it to master after the xtend build verified the changes.
Thanks again for your contribution.

**Comment by dhuebner** [comment]
@rovarga Merged into master

**Pull request merged**
