### PR TITLE
Bug 427909: StringConcatenation ca. >30% performance improvement

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=6236

**Comment by svenefftinge** [comment]
Thank you! The change looks good to me. Could you share a template that we can use to verify the 30% improvement?

**Comment by vorburger** [comment]
@svenefftinge the template that you can use to verify the improvement is attached on https://bugs.eclipse.org/bugs/show_bug.cgi?id=427909. (I confused issue IDs from two different bug trackers; I'll just push an updated commit with the correct ID.)

**Comment by kthoms** [comment]
The patch has a clear positive effect. I have attached the YourKit snapshots for both variants. Calls of StringConcatenation#append(Object,String) are reduced by 118 Mio. Calls.

The console output is on my machine:
```
BEFORE
=======
Min. 2065 - Max. 2137; Avg = 2101 (ms)
Min. 2062 - Max. 2087; Avg = 2074 (ms)
Min. 2077 - Max. 2137; Avg = 2107 (ms)
Min. 2125 - Max. 2205; Avg = 2165 (ms)
Min. 2164 - Max. 2260; Avg = 2212 (ms)

AFTER
=======
Min. 1309 - Max. 1356; Avg = 1332 (ms)
Min. 1295 - Max. 1324; Avg = 1309 (ms)
Min. 1293 - Max. 1341; Avg = 1317 (ms)
Min. 1311 - Max. 1395; Avg = 1353 (ms)
Min. 1309 - Max. 1368; Avg = 1338 (ms)

```

The patch introduces some new protected methods. Since they are considered to be API they need to be marked with `@since 2.11`. It should be considered if some of them could be private for now (e.g. the 3 new `appendSegment` (singular) methods or `continueSplitting`).

screenshot 86

[Bug427909_YourKit.zip](https://github.com/eclipse/xtext-lib/files/578062/Bug427909_YourKit.zip)

**Comment by rovarga** [comment]
My initial cut at them exposed them to keep the ability to override splitLinesAndNewLines() in a subclass. If that capability is not needed, I agree that the API surface of the class be kept as small as possible.

**Comment by vorburger** [comment]
@kthoms Thanks! As per your email, I've now squashed your 7660cb350b9f2a3dafb16f2b40ffab5bb0539279 and 6adda108496ae0dbd777d7942070a7f77ae58124 into this.  

@rovarga and I are looking forward to an active committer here (you @kthoms or @svenefftinge  @meysholdt @cdietrich @akosyakov) merging this one, as well as https://github.com/eclipse/xtext-lib/pull/17, so that it makes it into [the Xtend 2.11 release rescheduled for January 24th 2017](https://typefox.io/xtext-2-11-beta-1-is-here).. the sooner you merge both of our proposals, the earlier you noticed should the unexpected happen and this break anything! ;-)

**Comment by svenefftinge** [comment]
Thank you!

**Comment by dhuebner** [comment]
@svenefftinge This change seems to cause problems with downstream projects.
Without this change: http://services.typefox.io/open-source/jenkins/job/xtext-core/job/dh-testOlderLibBuild/1/ 
With this change: http://services.typefox.io/open-source/jenkins/job/xtext-core/job/dh-testOlderLibBuild/2/

**Comment by rovarga** [comment]
I think there is an uncaught regression around concatenation -- I noticed that while rebasing PR17 -- https://github.com/eclipse/xtext-lib/pull/17/commits/2f1e6b14d777c3a9eafbef266bcb5429d7df050c#diff-c03f880af676b9c7ad67eee571f53ae5R319 line 319.

**Comment by dhuebner** [comment]
@rovarga We need a test for that.

**Comment by dhuebner** [comment]
@rovarga @vorburger I have to revert the merge. So the downstream projects can be build again.

**Comment by rovarga** [comment]
@dhuebner Would you be willing to merge a one-liner fix instead?

**Comment by rovarga** [comment]
@dhuebner I don't seem to find a StringConcatenation test suite -- where should it live?

**Comment by rovarga** [comment]
Nevermind, it will need a bit more work than I can immediately throw at it :-(

**Comment by dhuebner** [comment]
@rovarga Sorry for that. We just need working downstream builds now.

**Comment by rovarga** [comment]
@dhuebner No worries, I know that not breaking downstream is always a priority.

**Comment by dhuebner** [comment]
Merged with https://github.com/eclipse/xtext-lib/pull/22

**Pull request merged**
