### PR TITLE
[489237] Generate hashCode in @EqualsHashCode more findbugs-friendly

### PR DESCRIPTION
**Pull request by cdietrich**
[489237] Generate hashCode in @EqualsHashCode more findbugs-friendly

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=489237

**Comment by cdietrich** [comment]
please review

**Comment by szarnekow** [comment]
Should be done for equals and the 'other' local var, too.

**Comment by cdietrich** [comment]
ok ill have a look

**Comment by cdietrich** [comment]
@szarnekow  adapted equals as well

**Comment by svenefftinge** [comment]
+1

**Pull request merged**
