### PR TITLE
Bug 427909: Expose overloaded StringConcatenation.append() methods

### PR DESCRIPTION
**Pull request by rovarga**
This exposes specialized String/StringConcatenation methods
so they can be used by javac to better bind at compile time.

### CODE REVIEW

**Comment by svenefftinge** [comment]
Hi @rovarga you would need to sign an ECA (https://www.eclipse.org/legal/ECA.php) before we can merge any contributions from you.

**Comment by rovarga** [comment]
Understood -- I am still waiting for my eclipse.org account to get validated so I can do so...

**Comment by rovarga** [comment]
Okay, all sorted now.

**Comment by svenefftinge** [comment]
Thank you, we will check your contributions around the performance improvements in the coming days.

**Comment by svenefftinge** [comment]
Could you please rebase it?

**Comment by rovarga** [comment]
@svenefftinge rebased to current master.

**Comment by rovarga** [comment]
Integrated into https://github.com/eclipse/xtext-lib/pull/21

**Pull request closed without merging**
