### PR TITLE
[389147] Add overloaded variants of InputOutput.print and println

### PR DESCRIPTION
**Pull request by cdietrich**
[389147] Add overloaded variants of InputOutput.print and println

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=389147

**Comment by cdietrich** [comment]
please review. do you have an idea how to test that?

**Comment by svenefftinge** [comment]
+1. No idea on how to test it, though.

**Comment by cdietrich** [comment]
ok i did some "manual" testing anyway

**Comment by szarnekow** [comment]
You could reassign System.out to a mocked print stream and check the called method. Not sure if that would be worth it.

**Comment by cdietrich** [comment]
this leads to follow up tests errors in org.eclipse.xtext.xbase.tests.typesystem.AbstractConstructorCallTypeTest.testDeferredTypeArgumentResolution_132()

@szarnekow @svenefftinge can you give me a pointer where this is done.
why does the type computation preferr a boxing method call over a direct method call?

maybe i have to revert this. what do you think

**Comment by cdietrich** [comment]
reverted the change

**Pull request merged**
