### PR TITLE
Added  toMap function which allows mapping of both keys and values

### PR DESCRIPTION
**Pull request by abies**
This combines existing toMap and toInvertedMap from Iterable/IteratorExtensions.

### CODE REVIEW

**Comment by abies** [comment]
I was not able to find unit tests for extension methods so I could add something. Are they in different project?

**Comment by abies** [comment]
Messed up due to CLA/sign-off requirement

**Comment by spoenemann** [comment]
> I was not able to find unit tests for extension methods so I could add something. Are they in different project?

Right, after the repository splitting there are no tests in this repository. We should add tests for new features and fixed bugs in this repository, preferably in the same project where the corresponding modified code is, using a new source folder 'test'.

**Comment by svenefftinge** [comment]
See #3

**Pull request closed without merging**
